In [ ]:
import os 
import pandas as pd 
import zipfile

with zipfile.ZipFile("./소상공인시장진흥공단_상가(상권)정보_20240331(수정).zip") as f:
    f.extractall("./commerical_data/")

In [11]:
path = "./commerical_data/"
total = []
for file in os.listdir(path):
    if file.split(".")[-1] == "csv":
        total.append(pd.read_csv(path + file , low_memory=False))

In [12]:
df1 = pd.concat(total)

In [ ]:
df1.shape

(2486672, 39)

In [14]:
del total

In [23]:
for x in df1[(df1.도로명주소.str.find('부천') > -1) &(df1.상호명.str.find('순대') > -1) ]['상호명']:
    print(x)

당아래가마솥순대국
발해순대국
할매전통순대국
순대랑왕족발
이소자순대국
소사순대
대치순대국
찹쌀순대
만복순대국오정
나연이네순대국
송내명가순대국
신림동순대타운
박지혜모던순대국&소머리국밥
청년순대국
정담순대국
할머니순대국
큰맘할매순대국
큰아들백순대
백순대본가새맛
곱창님순대님
봉암순대국밥
신의주찹쌀순대
이조옛날순대국
청년순대국
큰맘할매순대국신
한우리순대국
담소소사골순대부천역
정가네순대국
백암순대국
대치3순대국
할매순대국
임실왕순대족발
이가네순대국
신의주찹쌀순대
병천순대
형제가마솥순대국
병천순대국
병천순대
병천토속순대
신의주찹쌀순대와쭈꾸미신
신의주찹쌀순대
생삼겹살앤순대국
병천토속순대
복덩이순대국
그유명한덕이순대국
굿맘할매순대국&양선지해장국부천
역마차순대국
한우리순대국감자탕
배여사순대국
용추골순대국
개성진찹쌀순대
임실왕족발순대
우담순대국
이순대
소문난순대집
미각찹쌀순대
홍가순대국
병천순대
남가네설악추어탕;한모듬순대국
본래순대약대점
진천토종순대
토종순대국
논곡리토종순대국
병천토부리순대
병천황토방순대
이레순대
장수순대국
양씨네왕순대
옛날순대국
소문난순대집
토종순대국
신토리토속순대국
효자동순대국밥
신의주찹쌀순대
병천토속순대
궁중순대
원조찹쌀순대
신림순대곱창
인하찹쌀순대
진천토종순대
소문난순대국
가야본갈비순대국
풍미순대국
작동순대국
신토불이순대국
가마솥순대국
할매순대국
오복순대국솥밥
대치투순대국
삼거리순대국식당
이조명품순대국
할매순대국
담소사골순대송내역점
미가순대국
마촌순대국
최은미순대국
토종순대국
아빠손엄마손순대국
연산장터순대
부천가마솥순대국
대치순대
고향순대국
복사골순대
명가순대국
신의주찹쌀순대
개성진찹쌀순대
개성진찹쌀순대
순대상회
고향순대국
옥길순대국
큰맘할매순대국
임오순대국
임실순대국
아우네장터순대국
순대국이야기
시장순대국
민순자순대곱창
병천토속순대
원일순대국
승권씨네순대국
하예성순대국
진가네순대국
백가네토종순대국
약수진순대국
백가네토종순대국해장국
할매순대국도당동점
배불리찌개&순대국·감자탕
병천토속순대
시장순대국
다복백암순대
대치순대국
큰맘할매순대국부천삼정점
원주순대국
첫번째가마솥순대국
굿맘할매순대국&양선지해장국부천
대치순대국
신평양찹쌀순대
국민순대국부천고강점
배불리찌개&순대국감자탕
백암토종순대
백암토종순대국
두진옥순대국밥

In [30]:
df1.상권업종대분류명.unique()

array(['예술·스포츠', '음식', '수리·개인', '부동산', '숙박', '교육', '소매', '보건의료', '과학·기술',
       '시설관리·임대'], dtype=object)

In [29]:
df1.상권업종중분류명.unique()

array(['스포츠 서비스', '일식', '이용·미용', '한식', '기타 간이', '부동산 서비스', '일반 숙박',
       '기타 가정용품 수리', '기타 교육', '자동차 수리·세차', '중식', '가전·통신 소매',
       '섬유·의복·신발 소매', '시계·귀금속 소매', '의원', '의약·화장품 소매', '주점', '가전제품 수리',
       '식료품 소매', '유원지·오락', '시장 조사', '광고', '교육 지원', '고용 알선', '구내식당·뷔페',
       '비알코올 ', '오락용품 소매', '장식품 소매', '기술 서비스', '식물 소매', '일반 교육',
       '욕탕·신체관리', '인쇄·제품제작', '컴퓨터 수리', '종합 소매', '자동차 부품 소매', '세탁',
       '모터사이클 소매', '여행사·보조', '청소·방제', '병원', '가구 소매', '연료 소매', '도서관·사적지',
       '회계·세무', '사진 촬영', '중고 상품 소매', '기타 생활용품 소매', '전문 디자인', '서양식',
       '가정용품 대여', '법무관련 ', '산업용품 대여', '기타 상품 소매', '시설관리', '동남아시아',
       '본사·경영 컨설팅', '애완동물·용품 소매', '조경·유지', '기타 사업 서비스', '안경·정밀기기 소매',
       '기타 전문 과학', '철물·건설자재 소매', '수의', '사무 지원', '담배 소매', '운송장비 대여',
       '모터사이클 수리', '기타 보건', '장례식장 ', '음료 소매', '통신장비 수리', '기타 숙박', '기타 개인',
       '기타 외국'], dtype=object)

In [28]:
df1.상권업종소분류명.unique()

array(['테니스장', '일식 회/초밥', '피부 관리실', '국/탕/찌개류', '빵/도넛', '부동산 중개/대리업',
       '여관/모텔', '의류/이불 수선업', '태권도/무술학원', '치킨', '피자', '닭/오리고기 구이/찜',
       '자동차 정비소', '중국집', '미용실', '핸드폰 소매업', '백반/한정식', '유아용 의류 소매업',
       '여성 의류 소매업', '시계/귀금속 소매업', '산부인과 의원', '화장품 소매업', '요리 주점',
       '가전제품 수리업', '채소/과일 소매업', 'PC방', '시장 조사 및 여론 조사업', '광고 대행업',
       '건강보조식품 소매업', '요가/필라테스 학원', '기타 교육지원 서비스업', '임시/일용 인력 공급업', '구내식당',
       '카페', '그 외 기타 교육기관', '장난감 소매업', '돼지고기 구이/찜', '곱창 전골/구이', '예술품 소매업',
       '건축 설계 및 관련 서비스업', '꽃집', '기타 의원', '입시·교과학원', '목욕탕/사우나', '고용 알선업',
       '약국', '네일숍', '김밥/만두/분식', '명함/간판/광고물 제작', '버거', '신발 소매업',
       '컴퓨터/노트북/프린터 수리업', '가전제품 소매업', '슈퍼마켓', '노래방', '운동용품 소매업',
       '자동차 부품 소매업', '세탁소', '냉면/밀면', '모터사이클 및 부품 소매업', '일반 유흥 주점', '여행사',
       '기타 의류 소매업', '건축물 일반 청소업', '컴퓨터/소프트웨어 소매업', '국수/칼국수', '교육컨설팅업',
       '의료기기 소매업', '한의원', '일반병원', '음악학원', '가구 소매업', '해산물 구이/찜', '주유소',
       '편의점', '자동차 세차장', '독서실/스터디 카페', '횟집', '세무사', '침구류/커튼 소매업',
       '기타 오락장', '남성 의류 소매업', '사진촬영업', '중고 상품 소매업', '기타 예술/스포츠 교육기관',
       '전기용품/조명장치 소매업', '인테리어 디자인업', '경양식', '스포츠/레크리에이션 용품 대여업',
       '문구/회화용품 소매업', '옥외/전시 광고 대행업', '요양병원', '아이스크림/빙수', '당구장',
       '그 외 기타 개인/가정용품 수리업', '공인노무사', '건설기계/장비 대여업', '헬스장',
       '기타 기술/직업 훈련학원', '무도 유흥 주점', '그 외 기타 상품 전문 소매업', '체형/비만 관리',
       '족발/보쌈', '사업시설 유지·관리 서비스업', '베트남식 전문', '생맥주 전문', '경영 컨설팅업', '법무사',
       '미술학원', '내과/소아과 의원', '애완동물/애완용품 소매업', '일식 면 요리', '실/섬유제품 소매업',
       '시각 디자인업', '그 외 기타 간이 음식점', '마사지/안마', '조경 유지·관리 서비스업', '변호사',
       '전시/컨벤션/행사 대행 서비스업', '안경렌즈 소매업', '기타 산업용 기계/장비 대여업', '반찬/식료품 소매업',
       '정육점', '기타 한식 음식점', '주방/가정용품 소매업', '패밀리레스토랑', '광고물 설계/제작업',
       '사업/무형 재산권 중개업', '소고기 구이/찜', '떡/한과', '벽지/장판/마루 소매업', '골프 연습장',
       '기타 광고 관련 서비스업', '레크리에이션 교육기관', '셀프 빨래방', '동물병원', '탁구장', '복사업',
       '담배/전자담배 소매업', '가정용 연료 소매업', '토스트/샌드위치/샐러드', '자동차 대여업',
       '기타 엔지니어링 서비스업', '모터사이클 수리업', '치과의원', '마라탕/훠궈', '가죽/가방/신발 수선업',
       '기타 스포츠시설 운영업', '복권 발행/판매업', '유사 의료업', '산업설비; 운송장비 및 공공장소 청소업',
       '패션/섬유/기타 전문 디자인업', '컴퓨터 학원', '철물/공구 소매업', '변리사',
       '기타 여행 보조/예약 서비스업', '자전거 소매업', '공인회계사', '액세서리/잡화 소매업', '장례식장',
       '건어물/젓갈 소매업', '호텔/리조트', '그 외 기타 종합 소매업', '파스타/스테이크', '가방 소매업',
       '일식 카레/돈가스/덮밥', '소독; 구충 및 방제 서비스업', '기타 오락관련 서비스업', '컴퓨터/사무기기 대여업',
       '수산물 소매업', '생수/음료 소매업', '핸드폰/통신장비 수리업', '화장터/묘지/납골당',
       '기타 개인/가정용품 대여업', '외국어학원', '행정사', '주류 소매업', '수영장', '곡물/곡분 소매업',
       '타이어 소매업', '펜션', '직원 훈련기관', '종합 스포츠시설', '사회교육시설', '기숙사/고시원',
       '신경/정신과 의원', '복 요리 전문', '기타 일식 음식점', '상용 인력 공급 및 인사관리 서비스업',
       '건설/건축자재 소매업', '성형외과 의원', '서점', '건물 및 토목 엔지니어링 서비스업', '의류 대여업',
       '포장/충전업', '광고 매체 판매업', '기타 건설/건축자재 소매업', '결혼 상담 서비스업', '만화방',
       '기념품점', '제품 디자인업', '기타 서양식 음식점', '외과 의원', '가발 소매업',
       '환경 관련 엔지니어링 서비스업', '이비인후과 의원', '전자 게임장', '볼링장', '피부/비뇨기과 의원',
       '한복 소매업', '도시 계획 및 조경 설계 서비스업', '기타 사무 지원 서비스업', '전문자격/고시학원',
       '바둑/장기/체스 경기 운영업', '사진기/기타 광학기기 소매업', '기타 동남아식 전문', '뷔페', '한방병원',
       '캠핑/글램핑', '가스 충전소', '수상/해양 레저업', '예식장업', '번역/통역 서비스업',
       '시계/귀금속/악기 수리업', '사무기기 소매업', '얼음 소매업', '종합병원', '안과 의원', '악기 소매업',
       '운전학원', '스쿼시/라켓볼장', '치과병원', '음반/비디오물 소매업', '낚시터 운영업', '우유 소매업',
       '방사선 진단/병리 검사 의원', '청소년 수련시설', '음반/비디오물 대여업', '기타 운송장비 대여업',
       '가축 사료 소매업', '비디오방', '전/부침개', '기타 법무관련 서비스업', '아이스크림 할인점',
       '그 외 기타 숙박업', '기타 회계 관련 서비스업', '분류 안된 외국식 음식점'], dtype=object)

In [26]:
df1[df1.상호명 == "다복백암순대"]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
518220,MA0101202306A0076389,다복백암순대,NaN,I2,음식,I201,한식,I20102,국/탕/찌개류,I56111,...,4119910400102620003043469,해주아파트,경기도 부천시 오정구 소사로 814,421819.0,14412,NaN,1,NaN,126.80509,37.528724

# 서울시 25개 지역구별 커피전문점과 치킨집 현황 조사

In [37]:
df1[df1.상호명.str.find('교촌치킨') > -1]['상권업종소분류명'].unique()

array(['치킨'], dtype=object)

In [38]:
df1[df1.상호명.str.find('교촌치킨') > -1]['상권업종중분류명'].unique()

array(['기타 간이'], dtype=object)

In [39]:
df1[df1.상호명.str.find('교촌치킨') > -1]['상권업종대분류명'].unique()

array(['음식'], dtype=object)

In [42]:
df1.iloc[0]

상가업소번호            MA0101202210A0003881
상호명                            엉클몽키테니스
지점명                                NaN
상권업종대분류코드                           R1
상권업종대분류명                        예술·스포츠
상권업종중분류코드                         R103
상권업종중분류명                       스포츠 서비스
상권업종소분류코드                       R10312
상권업종소분류명                          테니스장
표준산업분류코드                        R91199
표준산업분류명                그 외 기타 스포츠 서비스업
시도코드                                27
시도명                              대구광역시
시군구코드                            27290
시군구명                               달서구
행정동코드                         27290625
행정동명                              상인2동
법정동코드                       2729011500
법정동명                               상인동
지번코드               2729011500114450004
대지구분코드                               1
대지구분명                               대지
지번본번지                           1445.0
지번부번지                              4.0
지번주소              대구광역시 달서구 상인동 1445-4
도로명코드                   272904241182.0
도로명                   대구광역시 달서구 상원로11길
건물본번지                             36.0
건물부번지                              NaN
건물관리번호       2729011500114450004013792
건물명                                NaN
도로명주소              대구광역시 달서구 상원로11길 36
구우편번호                         704817.0
신우편번호                            42790
동정보                                NaN
층정보                                  2
호정보                                NaN
경도                          128.535589
위도                           35.813599
Name: 0, dtype: object

In [48]:
치킨 = df1[(df1.상권업종소분류명 == '치킨') & (df1.시도명 == "서울특별시")].copy()

In [ ]:
df1[df1.상호명.str.find("스타벅스") > -1]

In [56]:
df1[df1.상호명.str.find("메가엠지씨커피") > -1]['상권업종소분류명'].unique()

array(['카페', '일반 유흥 주점', '요리 주점', '그 외 기타 간이 음식점', '가발 소매업', '핸드폰 소매업',
       '치킨', '유아용 의류 소매업', '슈퍼마켓', '화장품 소매업', '편의점'], dtype=object)

In [58]:
df1[(df1.상호명.str.find("메가엠지씨커피") > -1) & (df1.상권업종소분류명 == '핸드폰 소매업')]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
58602,MA010120220801210164,메가엠지씨커피간석오거리역점,NaN,G2,소매,G208,가전·통신 소매,G20802,핸드폰 소매업,G47312,...,2820010200102160011024486,도시에창,인천광역시 남동구 백범로 404,405804.0,21508,NaN,1,NaN,126.706538,37.467696

In [62]:
카페 = df1[(df1.상권업종소분류명 == '카페') & (df1.시도명 == "서울특별시")]

In [65]:
치킨_집계 = 치킨.groupby(['시군구명'])[['상호명']].count()

In [67]:
카페_집계 = 카페.groupby(['시군구명'])[['상호명']].count()

In [72]:
카페_집계

       상호명
시군구명
강남구   2076
강동구    726
강북구    485
강서구   1005
관악구    792
광진구    779
구로구    589
금천구    541
노원구    641
도봉구    392
동대문구   681
동작구    605
마포구   1939
서대문구   670
서초구   1204
성동구    787
성북구    787
송파구   1356
양천구    576
영등포구  1127
용산구    832
은평구    626
종로구   1185
중구    1000
중랑구    535

In [74]:
집계 = pd.merge(치킨_집계, 카페_집계, left_index=True,right_index=True, how='inner')

In [76]:
집계.columns  = ['치킨 매장 수', '커피 매장 수']

In [77]:
집계

      치킨 매장 수  커피 매장 수
시군구명
강남구       312     2076
강동구       232      726
강북구       191      485
강서구       312     1005
관악구       285      792
광진구       222      779
구로구       236      589
금천구       146      541
노원구       276      641
도봉구       186      392
동대문구      219      681
동작구       194      605
마포구       253     1939
서대문구      183      670
서초구       190     1204
성동구       169      787
성북구       241      787
송파구       329     1356
양천구       230      576
영등포구      235     1127
용산구       131      832
은평구       253      626
종로구       148     1185
중구        135     1000
중랑구       216      535